package tasks;


/**
* tasks/AdderTaskOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./HW01.idl
* Pondìlí, 6. bøezna 2023 19:54:28 CET
*/

public interface AdderTaskOperations  extends tasks.AbstractTask
{
  int a ();
  float b ();
  double result ();
  void result (double newResult);
} // interface AdderTaskOperations
