package tasks;


/**
* tasks/FlipLineTaskOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./HW01.idl
* Pondìlí, 6. bøezna 2023 19:54:28 CET
*/

public interface FlipLineTaskOperations  extends tasks.AbstractTask
{
  void update (tasks.Point[] flippedPolyLine, org.omg.CORBA.IntHolder lengthDifference);
} // interface FlipLineTaskOperations
