package tasks;


/**
* tasks/FlipLineTask.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./HW01.idl
* Pondìlí, 6. bøezna 2023 19:54:28 CET
*/

public interface FlipLineTask extends FlipLineTaskOperations, tasks.AbstractTask, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface FlipLineTask
