package tasks;


/**
* tasks/InitialTaskOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./HW01.idl
* Pondìlí, 6. bøezna 2023 19:54:28 CET
*/

public interface InitialTaskOperations 
{
  tasks.AbstractTask init (String email) throws tasks.TaskException;
} // interface InitialTaskOperations
