package tasks;


/**
* tasks/Point.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./HW01.idl
* Pondìlí, 6. bøezna 2023 19:54:28 CET
*/

public final class Point implements org.omg.CORBA.portable.IDLEntity
{
  public int x = (int)0;
  public int y = (int)0;

  public Point ()
  {
  } // ctor

  public Point (int _x, int _y)
  {
    x = _x;
    y = _y;
  } // ctor

} // class Point
