package tasks;


/**
* tasks/PolygonTaskOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./HW01.idl
* Pondìlí, 6. bøezna 2023 19:54:28 CET
*/

public interface PolygonTaskOperations  extends tasks.AbstractTask
{
  tasks.Point[] getPolyLine ();
  void sendResult (float polyLineLength);
} // interface PolygonTaskOperations
