package tasks;


/**
* tasks/PolyLineHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from ./HW01.idl
* Pondìlí, 6. bøezna 2023 19:54:28 CET
*/

abstract public class PolyLineHelper
{
  private static String  _id = "IDL:tasks/PolyLine:1.0";

  public static void insert (org.omg.CORBA.Any a, tasks.Point[] that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static tasks.Point[] extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = tasks.PointHelper.type ();
      __typeCode = org.omg.CORBA.ORB.init ().create_sequence_tc (0, __typeCode);
      __typeCode = org.omg.CORBA.ORB.init ().create_alias_tc (tasks.PolyLineHelper.id (), "PolyLine", __typeCode);
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static tasks.Point[] read (org.omg.CORBA.portable.InputStream istream)
  {
    tasks.Point value[] = null;
    int _len0 = istream.read_long ();
    value = new tasks.Point[_len0];
    for (int _o1 = 0;_o1 < value.length; ++_o1)
      value[_o1] = tasks.PointHelper.read (istream);
    return value;
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, tasks.Point[] value)
  {
    ostream.write_long (value.length);
    for (int _i0 = 0;_i0 < value.length; ++_i0)
      tasks.PointHelper.write (ostream, value[_i0]);
  }

}
